### ISSUE TITLE
Warning in plotting

### ISSUE THREAD

**Issue by sbridel** [widdowquinn/pyani#87] opened 2017-06-12 07:59 UTC
Warning coming from matplotlib

```INFO: Graphics method: seaborn
/home/sebastien/anaconda3/lib/python3.6/site-packages/matplotlib/cbook.py:136: MatplotlibDeprecationWarning: The axisbg attribute was deprecated in version 2.0. Use facecolor instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
/home/sebastien/anaconda3/lib/python3.6/site-packages/seaborn/matrix.py:143: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if xticklabels == []:
/home/sebastien/anaconda3/lib/python3.6/site-packages/seaborn/matrix.py:151: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if yticklabels == []:
```

**Comment by widdowquinn** [comment] 2017-06-12 10:32
Duplicate of #9

**Closed by widdowquinn** 2017-06-12 10:32 UTC
