### ISSUE TITLE
Providing short description for the plots

### ISSUE THREAD

**Issue by sbridel** [widdowquinn/pyani#60] opened 2017-03-27 11:44 UTC
Hello!

I was wondering if you can provide some short description for each graph output.
Like: 
- What the plot is showing
- How the values are computed
- How can we read the plot

Because, for some of them (e.g. Hadamard, similarity error, ..) I can't explain what's on the plot.
Thanks

**Comment by widdowquinn** [comment] 2018-08-30 10:45
Duplicate of #48

**Closed by widdowquinn** 2018-08-30 10:45 UTC
Labels: question
