### ISSUE TITLE
Continue stopped analysis with pyani v0.2.7

### ISSUE THREAD

**Issue by wn835166087** [widdowquinn/pyani#195] opened 2020-06-07 12:29 UTC
#### Summary:
Hi, my analysis on 141 genomes was topped for some reason, and I'm wondering is there a way to continue the analysis?
#### Description:
I used 
average_nucleotide_identity.py -i tests/test_ani_data/ -o tests/test_ANIm_output -m ANIm -g -v
and somehow it stopped (I assume pyani hasn't finished its analysis because (1)I only got output in the folder nucmer_output, which only contains .delta & .filter file. And I didn't got any summary file (2) for 141 genomes, if pairwise comparison is used, there should be 9870 comparisons, and I should get 19740 files in nucmer_output not 14263). I'm wondering is there a way to continue my analysis instead of rerunning it?#### Current Output:
The output you get from `pyani` or at the terminal, with this issue. It is very useful to know the current "wrong" behavior on your system.
### Operating System:
linux

**Comment by widdowquinn** [comment] 2020-06-07 13:39
Hi,

Thank you for using `pyani` - I'm sorry that you've encountered an issue. There are a couple of ways to proceed, from here.

With v0.2 I'm afraid you'd have to rerun the analysis. If you have access to the error message still, that would be helpful to diagnose what was going wrong. If you do not, then re-running and saving the output in a log file would be useful, as you could include the log file here for diagnosis.

The next version of `pyani` - v0.3 (not yet ready for `pypi`/`conda` release, sadly) would allow you to continue from where you left off. If you're familiar with installing from source, you could follow the instructions [here](https://pyani.readthedocs.io/en/latest/installation.html) (Section 3-installation from source).

This would then allow you to conduct ANIm analysis, as described [here](https://pyani.readthedocs.io/en/latest/quickstart.html). If the run fails and needs restarting, then any pre-calculated results can be re-used.

I'll not close the issue, just yet - please let me know how you get on.

L.

**Comment by wn835166087** [comment] 2020-06-07 16:21
Thank you for your quick response. I guess my program was stopped because
my remote connection to HPC broke (I shouldn't have gone sleep while the
program was running lol). Thanks for developing this nice program and
looking forward to the pip/conda version of your program!

Best,
Nan

**Comment by widdowquinn** [comment] 2020-06-07 17:10
Hi Nan,

I'm glad you found the cause of the issue - have you looked into `tmux` or `screen`? I use these on HPC to ensure persistence and let me log out while programs still run.

L.

**Closed** 2020-06-07 17:20 UTC
Labels: question

**Comment by wn835166087** [comment] 2020-06-07 18:16
Thank you. I'll try again with screen!
